apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: squirrly-rolebinding
  namespace: squirrly
subjects:
- kind: ServiceAccount
  name: squirrly-service-account
  namespace: squirrly
roleRef:
  kind: Role
  name: squirrly-role
  apiGroup: rbac.authorization.k8s.io

