apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: squirrelly-rolebinding
  namespace: squirrelly
subjects:
- kind: ServiceAccount
  name: squirrelly-service-account
  namespace: squirrelly
roleRef:
  kind: Role
  name: squirrelly-role
  apiGroup: rbac.authorization.k8s.io

