apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sample-job
  namespace: squirrly
subjects:
- kind: ServiceAccount
  name: sample-job
  namespace: squirrly
roleRef:
  kind: Role
  name: sample-job
  apiGroup: rbac.authorization.k8s.io

